MvcGrid/Models/Address.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcGrid.Models
{
    [Table("Addresses")]
    public class Address
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

MvcGrid/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcGrid.Models
{
    [Table("Countries")]
    public class Country
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Staff> Staffs { get; set; }
    }
}

MvcGrid/Models/Manager/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MvcGrid.Models.Manager
{
    public class DatabaseContext:DbContext
    {
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Address> Addresses { get; set; }

        public DatabaseContext()
        {
            Database.SetInitializer<DatabaseContext>(new Builder());
        }
    }

    public class Builder:CreateDatabaseIfNotExists<DatabaseContext>
    {
        protected override void Seed(DatabaseContext context)
        {
            List<Country> countryList = new List<Country>();
            for (int i = 0; i < 10; i++)
            {
                Country country = new Country();
                country.Name = FakeData.PlaceData.GetCountry();
                countryList.Add(country);
                context.Countries.Add(country);
            }
            context.SaveChanges();

            for (int i = 0; i < 100; i++)
            {
                Staff staff = new Staff();
                staff.FirstName = FakeData.NameData.GetFirstName();
                staff.LastName = FakeData.NameData.GetSurname();
                staff.Age = FakeData.NumberData.GetNumber(10, 90);

                Random random = new Random();
                int deger = random.Next(0, 10);

                staff.Country = countryList[deger];

                context.Staffs.Add(staff);
            }
            context.SaveChanges();
        }
    }
}

MvcGrid/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcGrid.Models
{
    [Table("Staffs")]
    public class Staff
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(50),Required]
        public string FirstName { get; set; }
        [StringLength(50), Required]
        public string LastName { get; set; }
        public int Age { get; set; }

        public Country Country { get; set; }
    }
}

MvcGrid/Controllers/GridController.cs
using MvcGrid.Models;
using MvcGrid.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcGrid.Controllers
{
    public class GridController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Grid
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {

            var model = db.Staffs.ToList();
            return View(model);
        }


        public ActionResult Add()
        {
            List<SelectListItem> countries = (
                from i in db.Countries.ToList()
                select new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }).ToList();

            ViewBag.Countries = countries;

            return View();
        }
        [HttpPost]
        public ActionResult Add(Staff staff)
        {
            var model = db.Countries.Where(x => x.Id == staff.Country.Id).FirstOrDefault();
            staff.Country = model;
            db.Staffs.Add(staff);
            db.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var staff = db.Staffs.Where(x => x.Id == id).FirstOrDefault();

            List<SelectListItem> countries = (
                from i in db.Countries.ToList()
                select new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }).ToList();

            ViewBag.Countries = countries;

            return View(staff);
        }

        [HttpPost]
        public ActionResult Edit(Staff staff)
        {
            var model = db.Staffs.Where(x => x.Id == staff.Id).FirstOrDefault();
            model.FirstName = staff.FirstName;
            model.LastName = staff.LastName;
            model.Age = staff.Age;

            var country = db.Countries.Where(x => x.Id == staff.Country.Id).FirstOrDefault();
            model.Country = country;

            db.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            if (id!=null)
            {
                var staff = db.Staffs.Where(x => x.Id == id).FirstOrDefault();
                if (staff!=null)
                {
                    db.Staffs.Remove(staff);

                    int deger = db.SaveChanges();
                    if (deger>0)
                    {
                        //veri tabanı etkilendi
                    }
                    else
                    {
                        //veri tabanı etkilenmedi
                    }
                }
            }

            return View();
        }
    }
}

MvcGrid/Controllers/HomeController.cs
using MvcGrid.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcGrid.Controllers
{
    public class HomeController : Controller
    {
        DatabaseContext db = new DatabaseContext();

        public ActionResult Index()
        {
            var model = db.Staffs.ToList();
            return View();
        }

        public ActionResult List()
        {

            var model = db.Staffs.ToList();
            return View(model);
        }


    }
}

MvcGrid/Views/Grid/Add.cshtml
@model MvcGrid.Models.Staff
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ekle</h2>
<br />

@using (Html.BeginForm())
{

    <div class="input-group">
        <span class="input-group-addon" id="txt_ad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", placeholder = "Adınızı Giriniz", aria_describedby = "txt_ad" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_soyad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", placeholder = "Soyadını Giriniz", aria_describedby = "txt_soyad" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_yas"><i class="glyphicon glyphicon-time"></i></span>
        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", placeholder = "Yaşınızı Giriniz", aria_describedby = "txt_yas" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_ulke"><i class="glyphicon glyphicon-globe"></i></span>
        @Html.DropDownListFor(x => x.Country.Id, (List<SelectListItem>)ViewBag.Countries, new { @class = "form-control", aria_describedby = "txt_ulke" })
    </div>
    <br />

    <input type="submit" class="btn btn-success" value="Kaydet" />
}

MvcGrid/Views/Grid/Delete.cshtml
@model MvcGrid.Models.Staff
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Başarıyla Silindi</h2>

@Html.ActionLink("Listeye Dön", "List", "Grid", null, new { @class="btn btn-warning"})

MvcGrid/Views/Grid/Edit.cshtml
@model MvcGrid.Models.Staff
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Düzenle</h2>
<br />
@using (Html.BeginForm())
{

    <div class="input-group">
        <span class="input-group-addon" id="txt_ad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", placeholder = "Adınızı Giriniz", aria_describedby = "txt_ad" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_soyad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", placeholder = "Soyadını Giriniz", aria_describedby = "txt_soyad" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_yas"><i class="glyphicon glyphicon-time"></i></span>
        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", placeholder = "Yaşınızı Giriniz", aria_describedby = "txt_yas" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_ulke"><i class="glyphicon glyphicon-globe"></i></span>
        @Html.DropDownListFor(x => x.Country.Id, (List<SelectListItem>)ViewBag.Countries, new { @class = "form-control", aria_describedby = "txt_ulke" })
    </div>
    <br />

    <input type="submit" class="btn btn-success" value="Kaydet" />
    @Html.HiddenFor(x=>x.Id)
}

MvcGrid/Views/Grid/List.cshtml
@model IEnumerable<MvcGrid.Models.Staff>
@using GridMvc.Html
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personelleri Listele</h2>

@Html.ActionLink("Ekle", "Add", "Grid", null, new { @class="btn btn-primary"})

@Html.Grid(Model).Columns(column =>
{
   column.Add(m => m.FirstName).Titled("Adlar").Sortable(true).Filterable(true);
   column.Add(m => m.LastName).Titled("Soyadlar").Sortable(true).Filterable(true);
   column.Add(m => m.Age).Titled("Yaşlar").Sortable(true).Filterable(true);
   column.Add()
   .Encoded(false)
   .Sanitized(false)
   .SetWidth(30)
   .RenderValueAs(x => Html.ActionLink("Düzenle", "Edit", "Grid", new { id = x.Id }, new { @class = "btn btn-warning" }));

   column.Add()
   .Encoded(false)
   .Sanitized(false)
   .SetWidth(30)
   .RenderValueAs(x => Html.ActionLink("Sil", "Delete", "Grid", new { id = x.Id }, new { @class = "btn btn-danger" }));

}).WithPaging(10)

MvcGrid/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MvcGrid/Views/Home/List.cshtml
@model IEnumerable<MvcGrid.Models.Staff>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Staff List</h2>

<ul class="list-group">
   @foreach (var item in Model)
    {
       <li class="list-group-item">
           @item.FirstName
       </li>
    }
</ul>

MvcGrid/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

MvcGrid/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

MvcGrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
</head>
<body>

    <div class="container body-content">
        <div class="col-md-3">

        </div>
        <div class="col-md-7">
            @RenderBody()
        </div>


    </div>


</body>
</html>